import React from 'react'

import type { Metadata } from 'next'
import BlogList from '@/components/blogList'

export const metadata: Metadata = {
  title: '这是首页列表',
  description: 'Generated by create next app',
}

const Home = () => (
  <div className='App'>
    <BlogList />
  </div>
)

export default Home
